namespace RbxlReader.DataTypes;
public enum PropertyType {
    Unknown,
    String,
    Bool,
    Int,
    Float,
    Double,
    UDim,
    UDim2,
    Ray,
    Faces,
    Axes,
    BrickColor,
    Color3,
    Vector2,
    Vector3,
    CFrame = 16,
    Quaternion,
    Enum,
    Ref,
    Vector3int16,
    NumberSequence,
    ColorSequence,
    NumberRange,
    Rect,
    PhysicalProperties,
    Color3uint8,
    Int64,
    SharedString,
    ProtectedString,
    OptionalCFrame,
    UniqueId,
    FontFace,
    SecurityCapabilities,
}